kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: httpd-ex-git
  labels:
    app: httpd-ex-git
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'httpd-ex-git:latest'
  resources: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'httpd:2.4-el7'
  source:
    type: Git
    git:
      uri: 'https://github.com/sclorg/httpd-ex.git'
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: httpd-ex-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: httpd-ex-git-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:ef5e1b11c6a68c4c4703338fc00052cdf2f000d10b0ff857aa99d49f726e0b72
    - type: ConfigChange
  runPolicy: Serial
