apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: testpod
spec:
  replicas: 2
  selector:
    app: testpod
  template:
    metadata:
      labels:
        app: testpod
    spec:
      containers:
      - image: quay.io/e27867/webtest
        name: testpod
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - mountPath: "/mnt"
          name: "pvtest"
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 100Mi
      volumes:
      - name: "pvtest"
        persistentVolumeClaim:
          claimName: "pvctest"
      env:
        - name: USERID
          valueFrom:
            secretKeyRef:
              name: secret-userinfo
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-userinfo
              key: password
