apiVersion: v1
kind: LimitRange
metadata:
  name: test-limitrange
spec:
  limits:
    - type: Pod
      max:
        cpu: 500m
        memory: 100Mi
#      min:
#        cpu: 10m
#        memory: 30Mi
    - type: Container
      default:
        cpu: 30m
        memory: 50Mi
      max:
        cpu: 500m
        memory: 100Mi
#      min:
#        cpu: 10m
#        memory: 30Mi
    