apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: pvtest
  name: pvtest
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/pv-data/pvtest
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem