apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: pvtest
  name: pvtest
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany  
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/pv-data/pvtest
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem