apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvctest
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: pvtest
  volumeMode: Filesystem
  volumeName: pvtest
