apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: testpod
spec:
  host: testpod-test.apps-crc.testing
  port:
    targetPort: 9080-tcp
#  tls:
#    termination: edge
#    termination: reencrypt
#    termination: passthrough
  to:
    kind: Service
    name: testpod
