apiVersion: v1
kind: Service
metadata:
  name: testpod
spec:
  ports:
  - name: 9080-tcp
    port: 9080
    targetPort: 9080
  - name: 9443-tcp
    port: 9443
    targetPort: 9443
  selector:
    app: testpod
  sessionAffinity: None
  type: ClusterIP